### ISSUE TITLE
Migration to OpenSSL 3

### ISSUE THREAD

**Issue by d94pn** [modelica/Encryption-and-Licensing#11]
The current toolkit implementation is based OpenSSL 1 which has reached end of life (11 Sep 2023). The tookit should hence be migrated to OpenSSL 3. We have already experienced practical issues due to this, where we try to combine QT 6 (based on OpenSSL 3) and the tookit, which leads to runtime crashes.

**Comment by axelmartenssonmodelon** [comment]
I can also add that I just now merged an improvement to how the test library is constructed in the build system (https://github.com/modelica/Encryption-and-Licensing/pull/12)

**Comment by d94pn** [comment]
Great! Which exact (minor) version of OpenSSL 3 did you migrate to?

**Comment by axelmartenssonmodelon** [comment]
We migrated to OpenSSL v3.0.8, see [src/cmake/BuildSemlaOpenSSL.cmake](https://github.com/modelica/Encryption-and-Licensing/blob/c0a96f82ce18e3033ab12874f8ec23b7e52484a1/src/cmake/BuildSemlaOpenSSL.cmake#L46)
