### ISSUE TITLE
mlle_tool_license: redundant package name parameter

### ISSUE THREAD

**Issue by d94pn** [modelica/Encryption-and-Licensing#5]
The SEMLA spec says:

```
"The container has one top-level directory for each contained top-level package (library)
...
Each top-level directory contains a directory “.library”.
...
If the library is encrypted, there are one or more LVEs, build with the same SSL and Randomizer keys."
```

So there should only be at most one package per LVE. Yet the function mlle_tool_license requires the package name as input. What is the point of that?

**Comment by axelmartenssonmodelon** [comment]
`mlle_tool_license()` is an extension point to support the requirement for ["Alternative, tool specific licensing mechanisms"](https://github.com/modelica/ModelicaSpecification/pull/2931/files#diff-cdc2b1d8271f8e1f93c5bb07badbf2a9d31a34ace36eee795c25e72f75217ac7R204) which the tool vendor and library vendor can agree upon. This is not part of the default implementation. Modelon doesn't use this currently.

**Comment by axelmartenssonmodelon** [comment]
We want to enable the use of the same LVE binary for multiple top-level packages (Modelica Libraries)
