### ISSUE TITLE
Unclear handling of multiple .moc files

### ISSUE THREAD

**Issue by d94pn** [modelica/Encryption-and-Licensing#6]
When a library contains multiple .moc files, it is unclear how the tool should handle them. Should it just open all of them automatically or only certain ones? There is also a security concern with encrypting indivudal files as remarked by Hans Olsson:

> And having encryption for individual files requires a lot of thought, and if there is no detailed description of that it is just an insecure mess. The basic issue is that if people can remove/disable specific sub-packages they can break the concealment in lots of ways.

**Comment by axelmartenssonmodelon** [comment]
There is a 1:1 mapping between .moc files and .mo files. When a library contains multiple .moc files, the tool could treat them in the same way as it treats multiple .mo files. The important part is that the tool checks the Protection annotation of all Modelica classes, and implements behavior that is in line with [Modelica Language Specification v3.6 section "18.9 Access Control to Protect Intellectual Property"](https://specification.modelica.org/maint/3.6/annotations.html#access-control-to-protect-intellectual-property). 

Files are not encrypted independently of each other. To prevent people from removing/disabling specific sub-packages, we generate a key mask of random bytes  for each package and sub-package. When deriving the encryption key for a specific file, we xor the library encryption key with the key masks for all parent packages.
